server:
  port: 8081

logging:
  level:
    root: info
    cc.yezj.rpc: debug

yezjrpc:
  app:
    id: app1
    namespace: public
    env: dev
    retries: 2
    timeout: 1200
    grayRatio: 100 # 范围0~100
  zkServer: localhost:2181
  zkNamespace: yezj