server:
  port: 9101

yezjrpc:
  app:
    id: app1
    namespace: public
    env: dev
    metas: "{gray: 'false',ids: 'bj',unit: 'B001'}"
  zkServer: localhost:2181
  zkNamespace: yezj


logging:
  level:
    root: info
    cc.yezj.rpc: debug